### ISSUE TITLE
ML to OF (PES 6)

### ISSUE THREAD

**Issue by AMIRELBAKRY** [lazanet/PES-Editor-6#5]
Hi there,

Is there any way to move (developed) Master League players into an Option File? (PES 6)

So to either:
**1. Move players from the Master League file to an Option File. (blue "ML" icon)
2. Move players from the My Team Data files to an Option File. (pink "M" icon)**

I couldn't find any other way to contact you, so that's why I'm doing it here.
If you can make this possible, I will donate to you for sure!
Hope to hear from you soon.

Thanks.

Amir

![87861950_10222131220694662_528798366348345344_o](https://user-images.githubusercontent.com/63584038/81730852-78224480-948e-11ea-90ff-9309c214fe0e.jpg)

**Comment by moth1995** [comment]
the first step i think it would be to decript those files so we can look into them to understand what they got inside, i recommend to you to look into this post [https://evo-web.co.uk/threads/unlock-secret-teams.78882/](url) there is an exe file that you can download and use to create an option file decripted (this way you can open it with hex editor and interpretate all of his data) then you can start a master league save the files and try to open it and see if is decripted  to try to understand the data and see if you can do that
